### PR TITLE
Fix typos.

### PR DESCRIPTION
**Pull request by keithrbennett**

### CODE REVIEW

**Comment by avdi** [comment]
Thanks!

**Comment by avdi** [comment]
I just realized that this was against README.markdown, not README.erb. This is going to get overwritten next time I push :-(

**Comment by keithrbennett** [comment]
I'll fix that.

**Comment by keithrbennett** [comment]
Hmmm...I made fixes and pushed them up to my fork in the fix-typos branch,
but can't see a way to issue a pull request.  I'm trying to figure out
what's going on...

- Keith

**Comment by keithrbennett** [comment]
Although Github did not offer to issue a pull request, I found a way to
explicitly request it, and have done that.

**Pull request merged**
